module Taler
  class Client
    @backend_url: untyped

    @password: untyped

    def initialize: (untyped backend_url, untyped password) -> void

    def request_token: () -> untyped

    def create_order: (untyped amount, untyped summary, untyped fulfillment_url) -> untyped

    def fetch_order: (untyped order_id) -> untyped

    private

    def auth_token: () -> ::String

    def get: (untyped url, ?untyped token) -> untyped

    def request: (untyped url, ?token: untyped, ?payload: untyped?) -> untyped
  end
end
