# GNU Taler payment system interface
module Taler
  VERSION: String

  # Base error class for errors raised in this module
  class Error < StandardError
  end

  # Order representation with convenient access to the merchant API.
  class Order
    # Connect an Order to the Taler merchant backend.
    # 
    # _@param_ `backend_url` — e.g. `"https://backend.demo.taler.net/instances/sandbox"`
    # 
    # _@param_ `password` — e.g. `"sandbox"`
    # 
    # _@param_ `id` — The order id of an existing order.
    # 
    # Connect to the official demo backend
    # ```ruby
    # Taler::Order.new(
    #   backend_url: "https://backend.demo.taler.net/instances/sandbox",
    #   password: "sandbox"
    # )
    # ```
    def initialize: (backend_url: String, password: String, ?id: String?) -> void

    # Create a new order record ready to take a payment.
    # 
    # _@param_ `amount` — e.g. "KUDOS:200"
    # 
    # _@param_ `summary` — A description of the order displayed to the user.
    # 
    # _@param_ `fulfillment_url` — The user is redirected to this URL after payment. The order status page also links here.
    # 
    # _@param_ `fulfillment_message` — Text to display to the user after payment.
    # 
    # _@return_ — The id of the new order.
    def create: (
                  amount: String,
                  summary: String,
                  ?fulfillment_url: String?,
                  ?fulfillment_message: String?
                ) -> String

    # The page where the customer can pay or accept a refund,
    # depending on the state of the order.
    # 
    # The merchant backend opens the Taler plugin or app if it can.
    # Otherwise it shows a QR code to scan in the app and provides
    # installation instructions.
    def status_url: () -> String

    # Access order status fields.
    # 
    # It queries the backend if it hasn't done that already.
    # Call {#reload} beforehand to get the latest status from the backend.
    # 
    # _@param_ `key` — A field in the order status response of the backend, e.g. `order_status`.
    # 
    # _@return_ — The value of the field.
    # Any simple type supported by JSON.
    # 
    # ```ruby
    # fetch("order_status") #=> "unpaid"
    # ```
    def fetch: (String key) -> (String | bool)

    # Query the latest order information from the backend.
    # 
    # If you called {#fetch} in the past and are expecting updates from
    # user interaction, you want to call this.
    # 
    # _@return_ — The order status returned by the backend.
    def reload: () -> ::Hash[untyped, untyped]

    # Issue a refund request for this order.
    # 
    # _@param_ `refund` — The amount with currency.
    # 
    # _@param_ `reason` — Why are you refunding?
    # 
    # _@return_ — Response from the merchant backend.
    def refund: (refund: String, reason: String) -> ::Hash[untyped, untyped]

    def inspect: () -> String

    def to_s: () -> String
  end

  # Access the GNU Taler merchant backend API.
  # 
  # See: https://docs.taler.net/core/api-merchant.html
  class Client
    # _@param_ `backend_url` — e.g. `"https://backend.demo.taler.net/instances/sandbox"`
    # 
    # _@param_ `password`
    def initialize: (String backend_url, String password) -> void

    # Obtain an access token to authenticate all other API calls.
    def request_token: () -> String

    # _@param_ `amount` — e.g. "KUDOS:200"
    # 
    # _@param_ `summary` — A description of the order displayed to the user.
    # 
    # _@param_ `fulfillment_url` — The user is redirected to this URL after payment. The order status page also links here.
    # 
    # _@param_ `fulfillment_message` — Text to display to the user after payment.
    # 
    # _@return_ — The resonse from the backend, usually just containing an
    # order id, e.g. `{order_id: "xxxxx"}`
    def create_order: (
                        amount: String,
                        summary: String,
                        ?fulfillment_url: String?,
                        ?fulfillment_message: String?
                      ) -> ::Hash[untyped, untyped]

    # _@param_ `order_id`
    def order_status_url: (String order_id) -> String

    # _@param_ `order_id`
    # 
    # _@return_ — The order status returned by the backend.
    def fetch_order: (String order_id) -> ::Hash[untyped, untyped]

    # _@param_ `order_id`
    # 
    # _@param_ `refund` — The amount with currency.
    # 
    # _@param_ `reason` — Why are you refunding?
    # 
    # _@return_ — Response from the merchant backend.
    def refund_order: (String order_id, refund: String, reason: String) -> ::Hash[untyped, untyped]

    def auth_token: () -> String

    # _@param_ `url`
    # 
    # _@param_ `token`
    # 
    # _@param_ `payload`
    def request: (String url, ?token: String, ?payload: ::Hash[untyped, untyped]?) -> String
  end
end